# Car configuration
motor:
  channel: 0
  zero_throttle: 0.05
  speed_to_throttle_ratio: 0.85
  speed:
    normal:
      forward: 0.27
      backward: -0.22
    fast:
        forward: 0.35
        backward: -0.22
    slow:
      forward: 0.1
      backward: -0.1
    zero: 0.0

wheel:
  channel: 1
  min_throttle: -1.0
  zero_throttle: 0.15
  max_throttle: 0.92

pwm:
  min_pulse: 1000
  max_pulse: 2000